# Job name and description for the "unknown-project" GitHub Action

name: "Unknown Project"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Unknown Project
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      - run: |
          npm install && npm test
          cp .env.example .env
          
      - name: Push changes to repository
        if: ${{ !contains(github.event.head_branch, 'master') }}
        uses: adricsamuel/push-to-origin@v1
        with:
          remoteName: unknown-project
          remoteEmail: unknown-